baseURL = 'https://trust2065.github.io/cursor_playground/'
languageCode = 'en-us'
title = '澳洲0-3歲育兒指南'
theme = 'ananke'

[params]
  description = 'Welcome to my blog'
  favicon = ''
  site_logo = ''
  facebook = ''
  twitter = ''
  instagram = ''
  youtube = ''
  github = ''
  gitlab = ''
  linkedin = ''
  mastodon = ''

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3